//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastleWindsorMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<auth_mapping> auth_mapping { get; set; }
        public virtual DbSet<auth_transfer> auth_transfer { get; set; }
        public virtual DbSet<ginamsg_account> ginamsg_account { get; set; }
        public virtual DbSet<ginamsg_account_validate> ginamsg_account_validate { get; set; }
        public virtual DbSet<ginamsg_account_validate2> ginamsg_account_validate2 { get; set; }
        public virtual DbSet<ginamsg_contact> ginamsg_contact { get; set; }
        public virtual DbSet<ginamsg_multi_im> ginamsg_multi_im { get; set; }
        public virtual DbSet<ginamsg_multi_im_validate> ginamsg_multi_im_validate { get; set; }
        public virtual DbSet<ginaoffice_multi_im> ginaoffice_multi_im { get; set; }
        public virtual DbSet<ginaoffice_task> ginaoffice_task { get; set; }
        public virtual DbSet<ginatalk_account> ginatalk_account { get; set; }
        public virtual DbSet<ginatalk_account_validate> ginatalk_account_validate { get; set; }
        public virtual DbSet<ginatalk_api_usage_log> ginatalk_api_usage_log { get; set; }
        public virtual DbSet<ginatalk_auth_client_mapping> ginatalk_auth_client_mapping { get; set; }
        public virtual DbSet<ginatalk_authorization> ginatalk_authorization { get; set; }
        public virtual DbSet<ginatalk_contact> ginatalk_contact { get; set; }
        public virtual DbSet<ginatalk_country_code_idx> ginatalk_country_code_idx { get; set; }
        public virtual DbSet<ginatalk_group> ginatalk_group { get; set; }
        public virtual DbSet<ginatalk_group_map> ginatalk_group_map { get; set; }
        public virtual DbSet<ginatalk_invitation> ginatalk_invitation { get; set; }
        public virtual DbSet<ginatalk_luis_log> ginatalk_luis_log { get; set; }
        public virtual DbSet<ginatalk_message> ginatalk_message { get; set; }
        public virtual DbSet<ginatalk_message_group> ginatalk_message_group { get; set; }
        public virtual DbSet<ginatalk_multi_group> ginatalk_multi_group { get; set; }
        public virtual DbSet<ginatalk_multi_group_mapping> ginatalk_multi_group_mapping { get; set; }
        public virtual DbSet<ginatalk_multi_im> ginatalk_multi_im { get; set; }
        public virtual DbSet<ginatalk_multi_im_validate> ginatalk_multi_im_validate { get; set; }
        public virtual DbSet<ginatalk_reminder_que> ginatalk_reminder_que { get; set; }
        public virtual DbSet<ginatalk_reminder_queue> ginatalk_reminder_queue { get; set; }
        public virtual DbSet<ginatalk_sms> ginatalk_sms { get; set; }
        public virtual DbSet<ginatalk_sys_log> ginatalk_sys_log { get; set; }
        public virtual DbSet<ginatalk_sys_user> ginatalk_sys_user { get; set; }
        public virtual DbSet<ginatalk_task> ginatalk_task { get; set; }
        public virtual DbSet<ginatalk_timezone> ginatalk_timezone { get; set; }
        public virtual DbSet<ginatalk_web_account> ginatalk_web_account { get; set; }
        public virtual DbSet<message> message { get; set; }
        public virtual DbSet<reminder_que> reminder_que { get; set; }
        public virtual DbSet<alexa_skill_auth_infos> alexa_skill_auth_infos { get; set; }
        public virtual DbSet<ginatalk_auth_client_redirect_uri> ginatalk_auth_client_redirect_uri { get; set; }
    }
}
