//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastleWindsorMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ginatalk_multi_group
    {
        public int guid { get; set; }
        public string group_code { get; set; }
        public string group_name { get; set; }
        public Nullable<int> is_private { get; set; }
        public string password { get; set; }
        public string owner_channel_id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
    }
}
