//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastleWindsorMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ginatalk_country_code_idx
    {
        public int guid { get; set; }
        public string country { get; set; }
        public string country_code { get; set; }
        public int country_code_len { get; set; }
        public string iso_codes { get; set; }
        public int phone_number_len { get; set; }
        public string language_code { get; set; }
        public string language_desc { get; set; }
        public Nullable<bool> supported { get; set; }
        public Nullable<int> sort_no { get; set; }
        public Nullable<bool> op_is_main { get; set; }
    }
}
