//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastleWindsorMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ginatalk_luis_log
    {
        public int guid { get; set; }
        public string channel { get; set; }
        public string channel_id { get; set; }
        public string account_phone_number { get; set; }
        public string app_id { get; set; }
        public string query { get; set; }
        public string intent { get; set; }
        public string full_result { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
    }
}
