//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastleWindsorMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ginatalk_authorization
    {
        public string client_id { get; set; }
        public string grant_type { get; set; }
        public string access_token { get; set; }
        public System.DateTime expired { get; set; }
        public string refresh_token { get; set; }
        public string scope { get; set; }
        public string account_phone_number { get; set; }
        public string channel { get; set; }
        public string channelId { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
    }
}
