//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastleWindsorMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ginatalk_sys_log
    {
        public int guid { get; set; }
        public string channel { get; set; }
        public string channel_id { get; set; }
        public string account_phone_number { get; set; }
        public string class_name { get; set; }
        public string function_name { get; set; }
        public string event_type { get; set; }
        public string event_message { get; set; }
        public System.DateTime create_time { get; set; }
    }
}
