//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastleWindsorMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ginamsg_account_validate2
    {
        public string channel_id { get; set; }
        public string channel { get; set; }
        public string account_phone_number { get; set; }
        public int validate_times { get; set; }
        public string validate_code { get; set; }
        public System.DateTime validate_expired { get; set; }
        public string validate_status { get; set; }
    }
}
