//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastleWindsorMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int Id { get; set; }
        public string recipient_account { get; set; }
        public string recipient_name { get; set; }
        public string recipient_channel { get; set; }
        public string sender_account { get; set; }
        public string sender_name { get; set; }
        public string sender_channel { get; set; }
        public string payload { get; set; }
        public string message_text { get; set; }
        public string action { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
    }
}
